name: Publish Python Package with Citation Update
on:
  release:
    types: [published]

permissions:
  contents: write
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: '3.11'
          enable-cache: true
      
      - name: Update CITATION.cff
        uses: recite/citation-sync@v1
        with:
          commit: true
          commit-message: "docs: update CITATION.cff for release ${{ github.ref_name }}"
          custom-fields: |
            {
              "repository-code": "${{ github.server_url }}/${{ github.repository }}",
              "url": "${{ github.server_url }}/${{ github.repository }}",
              "type": "software"
            }
      
      - name: Install dependencies and build
        run: |
          uv sync
          uv build
      
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1