name: Publish Python Package with Citation Update
on:
  release:
    types: [published]

permissions:
  contents: write
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      
      - name: Update CITATION.cff
        uses: your-username/citation-sync@v1
        with:
          commit: true
          commit-message: "docs: update CITATION.cff for release ${{ github.ref_name }}"
          custom-fields: |
            {
              "repository-code": "${{ github.server_url }}/${{ github.repository }}",
              "url": "${{ github.server_url }}/${{ github.repository }}",
              "type": "software"
            }
      
      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install build
      
      - name: Build package
        run: python -m build
      
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1